# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'goforeat_app' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for goforeat_app
  pod 'AppCenterReactNativeShared', '~> 1.3.0'
  pod 'AppCenter/Push', '~> 1.4.0'

  platform :ios, '9.0'
end
