# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'goforeat_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for Facebook sdk
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  # Pods for goforeat_app
#  pod 'AppCenterReactNativeShared', '~> 1.3.0'
#  pod 'AppCenter/Push', '~> 1.4.0'
#  pod 'JPush'

  platform :ios, '9.0'

#  pod 'Picker', :path => '../node_modules/react-native-picker'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
'Core',
'ART',
'RCTActionSheet',
'RCTGeolocation',
'RCTImage',
'RCTNetwork',
'RCTPushNotification',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket',
'RCTLinkingIOS',
'RCTAnimation',
'RCTBlob',
'DevSupport',
# 'BatchedBridge'
]

  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

#  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
          if target.name == "yoga"
              target.remove_from_project
          end
          if target.name == "RNCAsyncStorage"
              target.remove_from_project
          end
      end
  end

end
