# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'goforeat_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for Facebook sdk
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  # Pods for goforeat_app
#  pod 'AppCenterReactNativeShared', '~> 1.3.0'
#  pod 'AppCenter/Push', '~> 1.4.0'
#  pod 'JPush'

  platform :ios, '9.0'

#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#  pod 'Picker', :path => '../node_modules/react-native-picker'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
'Core',
'ART',
'RCTActionSheet',
'RCTGeolocation',
'RCTImage',
'RCTNetwork',
'RCTPushNotification',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket',
'RCTLinkingIOS',
'RCTAnimation',
'RCTBlob',
'DevSupport'
]

#  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  pod 'JPushRN', :path => '../node_modules/jpush-react-native'

end
